name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  schedule:
    - cron: '0 */3 * * *' # Runs every 3 hours
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Dependencies
        run: go mod tidy

      - name: Build site
        run: go run *.go --fetch --render
        env: 
          KOKKOS_DASHBOARD_TOKEN: ${{ secrets.KOKKOS_DASHBOARD_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload public directory
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
